### PR TITLE
Customize ssh service name

### PR DESCRIPTION
**Pull request by seefood**
I'm using a third party popular ssh module, and the service name is not 'ssh'. I prefer to make this module interact nicely with others than bend the more popular module to our needs :-) 

https://github.com/ghoneycutt/puppet-module-ssh/blob/master/manifests/init.pp#L809

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @seefood, thanks for the PR, can you take a look at the merge conflicts?

**Comment by seefood** [comment]
I will have to test this, to see no functionality is broken.

**Comment by juniorsysadmin** [comment]
@seefood This is failing lint tests, at the very least

**Comment by seefood** [comment]
merging and testing again...

**Comment by seefood** [comment]
A missing Comma? Really? your check is more strict than the official puppet-lint...

**Comment by dhoppe** [comment]
@seefood Thank you very much for your contribution.

**Pull request merged**
