### PR TITLE
add real systemwide functionality.

### PR DESCRIPTION
**Pull request by oscarsix**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @oscarsix, can you take a look at the failing spec tests?

**Comment by ffrank** [comment]
Weird: I see warnings in Travis, but no hard errors. Is the rake task failing on account of the warnings?

**Comment by bastelfreak** [comment]
@ffrank these are all puppet-lint warnings which we interpret as errors.

**Comment by bastelfreak** [comment]
Hi. Thanks for raising this PR, but I'm going to close it due to inactivity. Please reopen it if you're still interested in getting this merged.

**Pull request closed without merging**
